sequenceDiagram
  actor User
  participant Filter1
  participant Pipe1 as pipe-SA/ID
  participant Filter2
  participant Pipe2 as pipe-CA
  participant Filter4
  participant Pipe4 as pipe-SC/ID
  participant Filter3
  participant Pipe3 as pipe-SN/ID
  participant Filter6
  participant Pipe6 as pipe-SSN
  participant Filter7
  participant Pipe7 as pipe-SSG
  participant Filter5

  User->>Filter1: process()
  Filter1->>Pipe1: write(SA/ID)
  User->>Filter2: readCA()
  Filter2->>Pipe2: read() CA
  Pipe1->>Filter4: read() SA/ID
  Pipe2->>Filter4: read() CA
  Filter4->>Pipe4: readSC/ID()
  User->>Filter3: writeSN/ID(SN/ID)
  Filter3->>Pipe3: write(SN/ID)
  Pipe4->>Filter6: read() SC/ID
  Pipe3->>Filter6: read() SN/ID
  Filter6->>Pipe6: read() SSN
  Pipe6->>Filter7: read() SSN
  Filter7->>Pipe7: read() SSG
  Pipe7->>Filter5: read() SSG
  User->>Filter5: reportSSG()
